### ISSUE TITLE
Folding & Indentation

### ISSUE THREAD

**Issue by runxel** [GRAPHISOFT/vscode-gdl#1]
First of all thanks for this great extension from the guy who made the original Sublime Text extension!
Thanks to @pbaksa and the whole team for incorporating the wishes of Jochen, me, and others.
This is a successor well done.
And last but no least so great to have it finally being Open Source! 💯 

---

Two things I would like to see:
1. I think most people are using **indentation**, because it makes code navigation and overview so much easier. I'm calling to have indentation rules to be implemented.
More specifically [`On Enter Rules`](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#on-enter-rules).
So what's the differenc? "On Enter Rules" only come into play when the user types "Enter", while the normal indentation rules are also affecting the code if the user copies stuff. So former option might be a good compromies.
There is a lot that would benefit: Loops, Groups, Subroutines, just to name a few.
See example implementation down below.
2. **Custom Code Folding**.
I use code folding a lot, but sometimes it would be nice to have regions that are not determined by indentation to be foldable. The default way is that only indented code can be folded in VSC.
That's why we could define an extra special comment to gain the ability to fold arbitrary regions.

---

### Example Code
Note that slashes have to be escaped themself!

> 1. Indentation
```json
{
  "onEnterRules": [
    {
      "beforeText": "^.*\\s*(?:else|then)\\s*$",
      "action": { "indent": "indent" }
    },
	{
	  "beforeText": "^.*\\s*(?:endif)\\s*$",
      "action": { "indent": "outdent" }
    }
  ]
}
```

> 2. Code Folding
```json
{
  "folding": {
    "markers": {
      "start": "^\\s*!\\s*#?region\\b",
      "end": "^\\s*!\\s*#?endregion\\b"
    }
  }
}
```
This matches `!#region` and `!#endregion`.

**Comment by pbaksa** [comment]
Hi,

On enter formatting is a good idea, I would add lines ending with ,

Custom code folding coud be solved by using this addon: https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder

**Comment by runxel** [comment]
> On enter formatting is a good idea, I would add lines ending with ,

Yes! That is a good addition as well!
Thanks for considering this.

Regarding the code folding: I am aware of this addon, I even use(d) it. I just thought it would be great to have the native ability, since nobody is forced to use this functionality anyway, so it wouldn't hurt to provide this.
But I can understand the resistance for adding this. Again: Providing this wouldn't prevent any other feature, so there is really no trade-off at all to be considered.

**Comment by pbaksa** [comment]
Auto-identation done in v26.1
