### ISSUE TITLE
Confusing Intellisense

### ISSUE THREAD

**Issue by runxel** [GRAPHISOFT/vscode-gdl#2]
So nice to have that Intellisense support! I like it.

But the general layout could be improved.
Also I highly dislike the parameter type (`RealNum` in the example screenshot) being so intrusive in the Intellisense.
Look, actually this info belongs to the icon (whats now a generic box), and certainly not in the intellisense text! So instead of the box there should be the [icon of the appropiate type](https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions).

![intellisense1](https://user-images.githubusercontent.com/2277182/125359415-80b02c80-e36a-11eb-999c-75e669de3b13.png)

Even if you decide to leave it (which you really shouldn't), the order would still be wrong. I'm looking for a certain parameter so clearly the `RealNum` must not be named first....

And maybe the description of the parameter would do fine without the quotes wrapped around it.

**Comment by pbaksa** [comment]
Adding the parameter type to the text is useful because this allows parameter filtering by type. It could be after the parameter name.
I couldn't find how to customize icons, the existing ones are useless for the GDL parameter types. The type selection is done by the API [CompletionItemProvider](https://code.visualstudio.com/api/references/vscode-api#CompletionItemProvider) returning [CompletionItemKind](https://code.visualstudio.com/api/references/vscode-api#CompletionItemKind), no way to customize it's icon.

**Comment by runxel** [comment]
> Adding the parameter type to the text is useful because this allows parameter filtering by type. It could be after the parameter name.

By "filtering" you mean typing in e.g. `len_creal` (to take the example from the screenshot), or what?
(I actually can't test that right now, because intellisense has stopped working for me... no idea why, tho.)

🤔 Mh. Not that I would need that, but I can see that some few people might find it useful.

Still: This info clearly is not the info I want at the first place! It is a bit out of order.
How about writing:
```
param_name    (type)
```

---

I opened an issue at the VSC repo so maybe in the future we can register our own icons.

**Comment by pbaksa** [comment]
I meant typing LineType to see all linetype attribute parameters.
It works only with HSF gdl files and Ctrl-Alt-Space turns it on/off. If there is a bug and you can find a repro please report it.
I think I tried showing types at the end, but multiple spaces were collapsed to one. Parentheses might help visualy.

**Comment by runxel** [comment]
> I meant typing LineType to see all linetype attribute parameters.

Ah yes, okay. Now I understand. Thanks for clarification.
This might indeed be useful, especially when there are alot of the same type.

---

That was a weird one. Yesterday it refused to work, but today everythings fine again. ¯\_(ツ)_/¯
Thanks anyway!

**Comment by pbaksa** [comment]
Thank you for contributing!
