### ISSUE TITLE
Support 'goto definition'

### ISSUE THREAD

**Issue by runxel** [GRAPHISOFT/vscode-gdl#3]
Nice to have the outline, but it would be great if we could support the "goto definition" function of VSC as well.
This is especially helpful when having a lot of subroutines.
We could then place the cursor in the name and use the "goto definition" function to go to the subroutine in a fast way. Would speed up daily development for sure!

**Comment by pbaksa** [comment]
Thank you for contributing!

**Comment by runxel** [comment]
Sure!
What do I have to do to enable this function in v.1.25.2?
It does not seem to work for me....

**Comment by runxel** [comment]
Yeah I guessed so. But: Doesn't work for me (I never work with XML). Extension is uptodate.

**Comment by pbaksa** [comment]
Try editing the file, adding an enter, does it solve the issue?

For me a certain SCM extension loads the unmodified document in an invisible editor, which this extension handles unnecessarily. We will need to apply changes only of the active editor in GDLExtension.onDocumentChanged()

**Comment by runxel** [comment]
Ah, it seems that it somehow needs some kind of initialization. The trick with hitting enter worked!
