### ISSUE TITLE
Outline is too greedy

### ISSUE THREAD

**Issue by runxel** [GRAPHISOFT/vscode-gdl#4]
The outline is too greedy and will look into comments as well.

E.g. I epxlain the usage of my macros inside the comments.
This way the outline is suddenly cluttered with macro calls... but none of them are real, because they are actually comments.

This, naturally, should not be the case. Never look into comments.

**Comment by pbaksa** [comment]
It can be done easily assuming the ! is a comment and not part of a (possibly line-continued) string.
We will miss 
`s = "multi" + " \
! line" : call "macro"`
but it wouldn't be elegant code.

**Comment by runxel** [comment]
> but it wouldn't be elegant code.

That's true! What a horrible edge case 😄
I think we can safely ignore this possibility.
Explaining stuff in a comment is much more common.

**Comment by pbaksa** [comment]
Thank you for the feedback!
